
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaipcrtnldcevctgbseh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhaXBjcnRubGRjZXZjdGdic2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjkxNjksImV4cCI6MjA1ODU0NTE2OX0.paAQE5651XXeG2mJ4yatXIS3x6fA_oUqWFzMGXytXak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
